sudo: required
dist: trusty
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

env:
  - NODE_RELEASE=6.x
  - NOTE_RELEASE=7.x

cache:
  directories:
    - bower_components
    - node_modules

before_install:
  - sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}" | sudo -E bash -
  - sudo apt-get install -y nodejs
  - export PHPCS_DIR=/tmp/phpcs
  - export SNIFFS_DIR=/tmp/sniffs
  - git clone -b master --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git $PHPCS_DIR
  - git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $SNIFFS_DIR
  - $PHPCS_DIR/scripts/phpcs --config-set installed_paths $SNIFFS_DIR
  - phpenv rehash

install:
  - npm install -g npm@latest
  - npm install -g bower gulp yarn
  - yarn
  - bower install
  - composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require squizlabs/php_codesniffer

script:
  - php -v
  - node -v
  - npm -v
  - composer --version
  - npm run validate
  - $PHPCS_DIR/scripts/phpcs -p ./*.php --standard=ruleset.xml
